export const BLOG_CATEGORIES = [
  "Fragrance Reviews",
  "Perfume History",
  "Luxury Brands",
  "Seasonal Scents",
  "Fragrance Notes",
  "Celebrity Perfumes",
  "Vintage Perfumes",
  "Niche Fragrances",
  "Perfume Trends",
  "Fragrance Care",
  "Gift Guides",
  "Perfume Tips",
  "Brand Spotlights",
  "Fragrance Science",
  "Perfume Events"
] as const;

export const PERFUME_TAGS = [
  "floral",
  "woody",
  "citrus",
  "oriental",
  "fresh",
  "spicy",
  "vanilla",
  "musk",
  "rose",
  "jasmine",
  "sandalwood",
  "amber",
  "patchouli",
  "lavender",
  "bergamot",
  "leather",
  "tobacco",
  "gourmand",
  "aquatic",
  "powdery",
  "green",
  "fruity",
  "chypre",
  "fougere",
  "aldehydic"
] as const;
