// Migration Configuration
// Generated by setup script

module.exports = {
  "mysql": {
    "host": "localhost",
    "user": "root",
    "password": "",
    "database": "luxury_perfume_old",
    "port": 3306
  },
  "migration": {
    "skipExisting": true,
    "clearExisting": false,
    "useExistingImages": true,
    "imageBasePath": "/"
  }
};
