name: Optimize Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run image optimizer
        run: npm run optimize-images
      - name: Upload optimized images artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimized-images
          path: public/optimized
